import type { Metadata } from "next";
import { Geist, Geist_Mono, IBM_Plex_Serif, Nunito_Sans } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import ScrollToTop from "./components/ScrollToTop";
import { Poppins } from 'next/font/google';
import "./globals.css";

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  variable: '--font-poppins',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const IBM = IBM_Plex_Serif({
    weight: ["300"],
    style: ["italic"],
    subsets: ["latin"],
    variable: "--font-ibm",
});

const Noto = Nunito_Sans({
    weight: ["300","800"],
    subsets: ["latin"],
    variable: "--font-noto",
})


export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${geistSans.variable} ${geistMono.variable} ${IBM.variable} ${Noto.variable} antialiased min-h-screen`}
      >
    
        <Navbar/>
        {children}
        <ScrollToTop/>
        <Footer/>

       
      </body>
    </html>
  );
}
